#!/bin/bash
MCMODDIR=$(dirname $0)
source "$MCMODDIR/include/functions.sh"

FORGE=$(field_value "forge-version" "mcmod.server")

echo $FORGE

FILE=$(grep "^$FORGE=" "$MCMODDIR/minecraft-forge/" -rl)

VERSION=$(basename $FILE)

URL=$(field_value $FORGE $FILE)

echo $URL

JAR="forge-$FORGE.jar"
cached_download $JAR $URL

java -jar $JAR --installServer nogui

SERVERJAR=$(find . -regextype sed -regex "./forge-.*-universal.jar$")
echo java -jar $SERVERJAR nogui
if [ ! -f eula.txt ]; then
        java -jar $SERVERJAR nogui
fi
sed -i -e 's/eula=false/eula=true/g' eula.txt

mcmod-resolve-mods $VERSION