#!/bin/bash
MCMODDIR=$(dirname $0)
source "$MCMODDIR/include/functions.sh"

MCVERSION=$1

resolve_mod() {
        LINE=$1
        MOD=$(cut -d "=" -f 1 <<< $LINE)
        VERSION=$(cut -d "=" -f 2 <<< $LINE)
        mcmod-download $MOD $MCVERSION $VERSION "mods"
}

cat mcmod.modpack | while read LINE
do
        resolve_mod $LINE
done