#!/bin/bash
if [ "$1" = "--help" ] || [ "$1" = "--help" ] || [ -z "$1" ]; then
echo "Updates the information pertaining to a specific modpack version.
Usage:
  mcmod-update-version <mod> <minecraft-version> <mod-version> <url>"
exit 0
fi 

MOD=$1
MCVERSION=$2
VERSION=$3
URL=$4

if [ ! -d ./mods ]; then 
        mkdir ./mods
fi

cd ./mods

if [ ! -d ./$MOD ]; then 
        (>&2 echo "$MOD doesn't exist. Use mcmod-add to add the mod first")
        return 1
fi

cd ./$MOD

if grep -q $VERSION $MCVERSION; then
        LINE=$(grep $VERSION $MCVERSION)
        NL="$VERSION=$URL"
        REPLACE="s|${LINE}|${NL}|"
        echo $REPLACE
        sed -i $REPLACE ./$MCVERSION
else
        (>&2 echo "Version $VERSION of $MOD does not exist, use mcmod-add-version")
fi


