#!/bin/bash
if [ "$1" = "--help" ] || [ "$1" = "--help" ] || [ -z "$1" ]; then
echo Display help
exit 0
fi 

MOD=$1
URL=$2
DEPENDS=$3

if [ ! -d ./mods ]; then 
        mkdir ./mods
fi

cd ./mods

if [ ! -d ./$MOD ]; then 
        mkdir ./$MOD
        cd ./$MOD
else 
        (>&2 echo "$MOD already exists")
        return 1
fi

echo "url=$URL
depends=$DEPENDS" >> mod-info