#!/bin/bash
if [ "$1" = "--help" ] || [ "$1" = "--help" ] || [ -z "$1" ]; then
echo "Adds a version of a mod
Usage:
  mcmod-add-version <mod> <minecraft-version> <mod-version> <url>"
exit 0
fi 

MOD=$1
MCVERSION=$2
VERSION=$3
URL=$4

if [ ! -d ./mods ]; then 
        mkdir ./mods
fi

cd ./mods

if [ ! -d ./$MOD ]; then 
        (>&2 echo "$MOD doesn't exist. Use mcmod-add to add the mod first")
        return 1
fi

cd ./$MOD

if [ ! -f ./$MCVERSION ]; then
        touch ./$MCVERSION
fi

if grep -q $VERSION $MCVERSION; then
        (>&2 echo "Version $VERSION of $MOD already exists, use mcmod-update-version")
else
cat >> $MCVERSION << EOF
$VERSION=$URL
EOF
fi

