#!/bin/bash
if [ "$1" = "--help" ] || [ "$1" = "--help" ] || [ -z "$1" ]; then
echo "Gets the url to download a specific version of a mod.
Usage:
  mcmod-get-version-url <mod> <minecraft-version> <mod-version>"
exit 0
fi 
MCMODDIR=$(dirname $0)

MOD=$1
MCVERSION=$2
VERSION=$3

FILE=$(readlink -f "$MCMODDIR/mods/$MOD/$MCVERSION")

REGEX="^$VERSION="
LINE=$(grep $REGEX $FILE)

if [[ -z $LINE ]]; then
        echo "Version $VERSION not found" >&2
        exit 1
else
NUMBER=$(cut -d "=" -f 2 <<< $LINE)

echo $NUMBER
fi
