#!/bin/bash
if [ "$1" = "--help" ] || [ "$1" = "--help" ] || [ -z "$1" ]; then
echo "Downloads the specified version of a mod if it doesn't already exist
Usage:
  mcmod-download <mod> <minecraft-version> <mod-version> <output-directory>"
exit 0
fi 

MOD=$1
MCVERSION=$2
VERSION=$3
TARGET=$4

URL=$(./mcmod-get-version-url $MOD $MCVERSION $VERSION)
echo $URL

# Save working directory for later
WORKINGDIR="$PWD"

if [ -z "$TARGET" ]; then
        TARGET=$WORKINGDIR
fi

if ! cd $TARGET; then
        echo Does not Exist
        exit 1
fi

cd $TARGET
if [ -f $FILE ]
# Logic to download past bot protection on Curse
if [[ $URL =~ ^https:\/\/mods\.curse\.com\/mc-mods\/minecraft\/ ]]; then
URL=$(wget -O - -o /dev/null  $URL |  sed ':a:N:$!ba;s/\"/\n/g' \
| grep http://addons.curse.cursecdn.com/)
echo "Sleeping for 2 seconds to comply with Curse Terms of Service"
sleep 2
fi

wget $URL -O "$MOD-$MCVERSION-$VERSION.jar" -nc